#!/usr/bin/env bash

echo '[WARNING] gscam_node is an interim dependency and will be removed in the next release! Please change all launchfiles back to use "gscam" instead of "gscam_node"'

/home/i3dr/i3dr_tools_ros/i3dr_tools_ros_WS/devel/lib/gscam/gscam
