set(_CATKIN_CURRENT_PACKAGE "uno_imu")
set(uno_imu_VERSION "0.0.0")
set(uno_imu_MAINTAINER "htp <htp@todo.todo>")
set(uno_imu_PACKAGE_FORMAT "2")
set(uno_imu_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "serial" "sensor_msgs" "tf")
set(uno_imu_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs" "serial" "sensor_msgs" "tf")
set(uno_imu_BUILDTOOL_DEPENDS "catkin")
set(uno_imu_BUILDTOOL_EXPORT_DEPENDS )
set(uno_imu_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "serial" "sensor_msgs" "imu_filter_madgwick" "rtabmap" "tf")
set(uno_imu_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "serial" "sensor_msgs" "imu_filter_madgwick" "rtabmap" "tf")
set(uno_imu_TEST_DEPENDS )
set(uno_imu_DOC_DEPENDS )
set(uno_imu_URL_WEBSITE "")
set(uno_imu_URL_BUGTRACKER "")
set(uno_imu_URL_REPOSITORY "")
set(uno_imu_DEPRECATED "")