set(_CATKIN_CURRENT_PACKAGE "i3dr_phobos")
set(i3dr_phobos_VERSION "0.0.1")
set(i3dr_phobos_MAINTAINER "Josh Veitch-Michaelis <jveitch@i3drobotics.com>")
set(i3dr_phobos_PACKAGE_FORMAT "2")
set(i3dr_phobos_BUILD_DEPENDS "roscpp" "camera_info_manager" "image_transport" "nodelet" "sensor_msgs" "libv4l-dev" "gscam>")
set(i3dr_phobos_BUILD_EXPORT_DEPENDS "roscpp" "camera_info_manager" "image_transport" "nodelet" "sensor_msgs" "libv4l-dev" "gscam>")
set(i3dr_phobos_BUILDTOOL_DEPENDS "catkin")
set(i3dr_phobos_BUILDTOOL_EXPORT_DEPENDS )
set(i3dr_phobos_EXEC_DEPENDS "roscpp" "camera_info_manager" "image_transport" "nodelet" "sensor_msgs" "libv4l-dev" "gscam>")
set(i3dr_phobos_RUN_DEPENDS "roscpp" "camera_info_manager" "image_transport" "nodelet" "sensor_msgs" "libv4l-dev" "gscam>")
set(i3dr_phobos_TEST_DEPENDS )
set(i3dr_phobos_DOC_DEPENDS )
set(i3dr_phobos_URL_WEBSITE "http://i3drobotics.com/phobos")
set(i3dr_phobos_URL_BUGTRACKER "")
set(i3dr_phobos_URL_REPOSITORY "")
set(i3dr_phobos_DEPRECATED "")