# CMake generated Testfile for 
# Source directory: /home/i3dr/i3dr_tools_ros/i3dr_tools_ros_WS/src
# Build directory: /home/i3dr/i3dr_tools_ros/i3dr_tools_ros_WS/build-src-Desktop-Default
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
subdirs(i3dr_cameras/image_pipeline/image_pipeline)
subdirs(i3dr_robot_interface/universal_robot/universal_robot)
subdirs(i3dr_robot_interface/universal_robot/universal_robots)
subdirs(i3dr_robot_interface/universal_robot/ur_description)
subdirs(i3dr_robot_interface/universal_robot/ur_e_description)
subdirs(i3dr_robot_interface/universal_robot/ur_msgs)
subdirs(i3dr_cameras/image_pipeline/camera_calibration)
subdirs(i3dr_cameras/realsense/ddynamic_reconfigure)
subdirs(i3dr_cameras/gscam)
subdirs(i3dr_cameras/i3dr_phobos-ros)
subdirs(i3dr_cameras/i3dr_phobos_nuclear-ros)
subdirs(i3dr_cameras/image_pipeline/image_proc)
subdirs(i3dr_cameras/image_pipeline/image_publisher)
subdirs(i3dr_cameras/image_pipeline/image_view)
subdirs(i3dr_cameras/image_pipeline/stereo_image_proc)
subdirs(i3dr_cameras/image_pipeline/depth_image_proc)
subdirs(i3dr_registration_localisation/i3dr_registration_localisation)
subdirs(i3dr_robot_interface/i3dr_UR10)
subdirs(i3dr_cameras/realsense/realsense2_camera)
subdirs(i3dr_cameras/i3dr_realsense-ros)
subdirs(i3dr_cameras/image_pipeline/image_rotate)
subdirs(i3dr_registration_localisation/uno_imu)
subdirs(i3dr_robot_interface/universal_robot/ur_bringup)
subdirs(i3dr_robot_interface/universal_robot/ur_driver)
subdirs(i3dr_robot_interface/universal_robot/ur_e_gazebo)
subdirs(i3dr_robot_interface/universal_robot/ur_gazebo)
subdirs(i3dr_robot_interface/universal_robot/ur_modern_driver)
subdirs(i3dr_robot_interface/universal_robot/ur_kinematics)
subdirs(i3dr_cameras/i3dr_deimos-ros)
subdirs(i3dr_cameras/i3dr_stereo_camera-ros)
subdirs(i3dr_robot_interface/universal_robot/ur10_e_moveit_config)
subdirs(i3dr_robot_interface/universal_robot/ur10_moveit_config)
subdirs(i3dr_robot_interface/universal_robot/ur3_e_moveit_config)
subdirs(i3dr_robot_interface/universal_robot/ur3_moveit_config)
subdirs(i3dr_robot_interface/universal_robot/ur5_e_moveit_config)
subdirs(i3dr_robot_interface/universal_robot/ur5_moveit_config)
