set(_CATKIN_CURRENT_PACKAGE "i3dr_stereo_camera")
set(i3dr_stereo_camera_VERSION "0.0.1")
set(i3dr_stereo_camera_MAINTAINER "Ben Knight <bknight@i3drobotics.com>")
set(i3dr_stereo_camera_PACKAGE_FORMAT "2")
set(i3dr_stereo_camera_BUILD_DEPENDS "roscpp" "camera_info_manager" "image_transport" "nodelet" "sensor_msgs" "xacro" "joint_state_publisher" "stereo_image_proc" "robot_state_publisher" "std_msgs" "dynamic_reconfigure" "pcl_ros" "cv_bridge")
set(i3dr_stereo_camera_BUILD_EXPORT_DEPENDS "roscpp" "camera_info_manager" "image_transport" "nodelet" "sensor_msgs" "xacro" "joint_state_publisher" "stereo_image_proc" "robot_state_publisher" "std_msgs" "dynamic_reconfigure" "pcl_ros" "cv_bridge")
set(i3dr_stereo_camera_BUILDTOOL_DEPENDS "catkin")
set(i3dr_stereo_camera_BUILDTOOL_EXPORT_DEPENDS )
set(i3dr_stereo_camera_EXEC_DEPENDS "roscpp" "camera_info_manager" "image_transport" "nodelet" "sensor_msgs" "xacro" "joint_state_publisher" "stereo_image_proc" "robot_state_publisher" "std_msgs" "dynamic_reconfigure" "pcl_ros" "cv_bridge")
set(i3dr_stereo_camera_RUN_DEPENDS "roscpp" "camera_info_manager" "image_transport" "nodelet" "sensor_msgs" "xacro" "joint_state_publisher" "stereo_image_proc" "robot_state_publisher" "std_msgs" "dynamic_reconfigure" "pcl_ros" "cv_bridge")
set(i3dr_stereo_camera_TEST_DEPENDS )
set(i3dr_stereo_camera_DOC_DEPENDS )
set(i3dr_stereo_camera_URL_WEBSITE "http://i3drobotics.com/")
set(i3dr_stereo_camera_URL_BUGTRACKER "")
set(i3dr_stereo_camera_URL_REPOSITORY "")
set(i3dr_stereo_camera_DEPRECATED "")