// Generated by gencpp from file i3dr_stereo_camera/SetFloat.msg
// DO NOT EDIT!


#ifndef I3DR_STEREO_CAMERA_MESSAGE_SETFLOAT_H
#define I3DR_STEREO_CAMERA_MESSAGE_SETFLOAT_H

#include <ros/service_traits.h>


#include <i3dr_stereo_camera/SetFloatRequest.h>
#include <i3dr_stereo_camera/SetFloatResponse.h>


namespace i3dr_stereo_camera
{

struct SetFloat
{

typedef SetFloatRequest Request;
typedef SetFloatResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetFloat
} // namespace i3dr_stereo_camera


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::i3dr_stereo_camera::SetFloat > {
  static const char* value()
  {
    return "96fbe2a49585a736ad8b4a31afbaf099";
  }

  static const char* value(const ::i3dr_stereo_camera::SetFloat&) { return value(); }
};

template<>
struct DataType< ::i3dr_stereo_camera::SetFloat > {
  static const char* value()
  {
    return "i3dr_stereo_camera/SetFloat";
  }

  static const char* value(const ::i3dr_stereo_camera::SetFloat&) { return value(); }
};


// service_traits::MD5Sum< ::i3dr_stereo_camera::SetFloatRequest> should match 
// service_traits::MD5Sum< ::i3dr_stereo_camera::SetFloat > 
template<>
struct MD5Sum< ::i3dr_stereo_camera::SetFloatRequest>
{
  static const char* value()
  {
    return MD5Sum< ::i3dr_stereo_camera::SetFloat >::value();
  }
  static const char* value(const ::i3dr_stereo_camera::SetFloatRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::i3dr_stereo_camera::SetFloatRequest> should match 
// service_traits::DataType< ::i3dr_stereo_camera::SetFloat > 
template<>
struct DataType< ::i3dr_stereo_camera::SetFloatRequest>
{
  static const char* value()
  {
    return DataType< ::i3dr_stereo_camera::SetFloat >::value();
  }
  static const char* value(const ::i3dr_stereo_camera::SetFloatRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::i3dr_stereo_camera::SetFloatResponse> should match 
// service_traits::MD5Sum< ::i3dr_stereo_camera::SetFloat > 
template<>
struct MD5Sum< ::i3dr_stereo_camera::SetFloatResponse>
{
  static const char* value()
  {
    return MD5Sum< ::i3dr_stereo_camera::SetFloat >::value();
  }
  static const char* value(const ::i3dr_stereo_camera::SetFloatResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::i3dr_stereo_camera::SetFloatResponse> should match 
// service_traits::DataType< ::i3dr_stereo_camera::SetFloat > 
template<>
struct DataType< ::i3dr_stereo_camera::SetFloatResponse>
{
  static const char* value()
  {
    return DataType< ::i3dr_stereo_camera::SetFloat >::value();
  }
  static const char* value(const ::i3dr_stereo_camera::SetFloatResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // I3DR_STEREO_CAMERA_MESSAGE_SETFLOAT_H
