// Generated by gencpp from file i3dr_stereo_camera/SetInt.msg
// DO NOT EDIT!


#ifndef I3DR_STEREO_CAMERA_MESSAGE_SETINT_H
#define I3DR_STEREO_CAMERA_MESSAGE_SETINT_H

#include <ros/service_traits.h>


#include <i3dr_stereo_camera/SetIntRequest.h>
#include <i3dr_stereo_camera/SetIntResponse.h>


namespace i3dr_stereo_camera
{

struct SetInt
{

typedef SetIntRequest Request;
typedef SetIntResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetInt
} // namespace i3dr_stereo_camera


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::i3dr_stereo_camera::SetInt > {
  static const char* value()
  {
    return "41a6318c88ca9d75d7a585e2aa4ca6ea";
  }

  static const char* value(const ::i3dr_stereo_camera::SetInt&) { return value(); }
};

template<>
struct DataType< ::i3dr_stereo_camera::SetInt > {
  static const char* value()
  {
    return "i3dr_stereo_camera/SetInt";
  }

  static const char* value(const ::i3dr_stereo_camera::SetInt&) { return value(); }
};


// service_traits::MD5Sum< ::i3dr_stereo_camera::SetIntRequest> should match 
// service_traits::MD5Sum< ::i3dr_stereo_camera::SetInt > 
template<>
struct MD5Sum< ::i3dr_stereo_camera::SetIntRequest>
{
  static const char* value()
  {
    return MD5Sum< ::i3dr_stereo_camera::SetInt >::value();
  }
  static const char* value(const ::i3dr_stereo_camera::SetIntRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::i3dr_stereo_camera::SetIntRequest> should match 
// service_traits::DataType< ::i3dr_stereo_camera::SetInt > 
template<>
struct DataType< ::i3dr_stereo_camera::SetIntRequest>
{
  static const char* value()
  {
    return DataType< ::i3dr_stereo_camera::SetInt >::value();
  }
  static const char* value(const ::i3dr_stereo_camera::SetIntRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::i3dr_stereo_camera::SetIntResponse> should match 
// service_traits::MD5Sum< ::i3dr_stereo_camera::SetInt > 
template<>
struct MD5Sum< ::i3dr_stereo_camera::SetIntResponse>
{
  static const char* value()
  {
    return MD5Sum< ::i3dr_stereo_camera::SetInt >::value();
  }
  static const char* value(const ::i3dr_stereo_camera::SetIntResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::i3dr_stereo_camera::SetIntResponse> should match 
// service_traits::DataType< ::i3dr_stereo_camera::SetInt > 
template<>
struct DataType< ::i3dr_stereo_camera::SetIntResponse>
{
  static const char* value()
  {
    return DataType< ::i3dr_stereo_camera::SetInt >::value();
  }
  static const char* value(const ::i3dr_stereo_camera::SetIntResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // I3DR_STEREO_CAMERA_MESSAGE_SETINT_H
