
#ifndef JR_PHOBOS_PHOBOSINTEGRATION_EXPORT_H
#define JR_PHOBOS_PHOBOSINTEGRATION_EXPORT_H

#ifdef JR_PHOBOS_PHOBOSINTEGRATION_STATIC_DEFINE
#  define JR_PHOBOS_PHOBOSINTEGRATION_EXPORT
#  define JR_PHOBOS_PHOBOSINTEGRATION_NO_EXPORT
#else
#  ifndef JR_PHOBOS_PHOBOSINTEGRATION_EXPORT
#    ifdef PhobosIntegration_EXPORTS
        /* We are building this library */
#      define JR_PHOBOS_PHOBOSINTEGRATION_EXPORT __attribute__((visibility("default")))
#    else
        /* We are using this library */
#      define JR_PHOBOS_PHOBOSINTEGRATION_EXPORT __attribute__((visibility("default")))
#    endif
#  endif

#  ifndef JR_PHOBOS_PHOBOSINTEGRATION_NO_EXPORT
#    define JR_PHOBOS_PHOBOSINTEGRATION_NO_EXPORT __attribute__((visibility("hidden")))
#  endif
#endif

#ifndef JR_PHOBOS_PHOBOSINTEGRATION_DEPRECATED
#  define JR_PHOBOS_PHOBOSINTEGRATION_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef JR_PHOBOS_PHOBOSINTEGRATION_DEPRECATED_EXPORT
#  define JR_PHOBOS_PHOBOSINTEGRATION_DEPRECATED_EXPORT JR_PHOBOS_PHOBOSINTEGRATION_EXPORT JR_PHOBOS_PHOBOSINTEGRATION_DEPRECATED
#endif

#ifndef JR_PHOBOS_PHOBOSINTEGRATION_DEPRECATED_NO_EXPORT
#  define JR_PHOBOS_PHOBOSINTEGRATION_DEPRECATED_NO_EXPORT JR_PHOBOS_PHOBOSINTEGRATION_NO_EXPORT JR_PHOBOS_PHOBOSINTEGRATION_DEPRECATED
#endif

#define DEFINE_NO_DEPRECATED 0
#if DEFINE_NO_DEPRECATED
# define JR_PHOBOS_PHOBOSINTEGRATION_NO_DEPRECATED
#endif

#endif
