set(_CATKIN_CURRENT_PACKAGE "i3dr_ur10")
set(i3dr_ur10_VERSION "0.0.1")
set(i3dr_ur10_MAINTAINER "Ben Knight <bknight@i3drobotics.com>")
set(i3dr_ur10_PACKAGE_FORMAT "2")
set(i3dr_ur10_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "std_srvs" "cv_bridge" "image_transport" "message_filters" "tf")
set(i3dr_ur10_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs" "std_srvs" "cv_bridge" "image_transport" "message_filters" "tf")
set(i3dr_ur10_BUILDTOOL_DEPENDS "catkin")
set(i3dr_ur10_BUILDTOOL_EXPORT_DEPENDS )
set(i3dr_ur10_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "std_srvs" "cv_bridge" "image_transport" "message_filters" "tf")
set(i3dr_ur10_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "std_srvs" "cv_bridge" "image_transport" "message_filters" "tf")
set(i3dr_ur10_TEST_DEPENDS )
set(i3dr_ur10_DOC_DEPENDS )
set(i3dr_ur10_URL_WEBSITE "http://i3drobotics.com/")
set(i3dr_ur10_URL_BUGTRACKER "")
set(i3dr_ur10_URL_REPOSITORY "")
set(i3dr_ur10_DEPRECATED "")