set(_CATKIN_CURRENT_PACKAGE "i3dr_phobos_nuclear")
set(i3dr_phobos_nuclear_VERSION "0.0.1")
set(i3dr_phobos_nuclear_MAINTAINER "Josh Veitch-Michaelis <bknight@i3drobotics.com>")
set(i3dr_phobos_nuclear_PACKAGE_FORMAT "2")
set(i3dr_phobos_nuclear_BUILD_DEPENDS "roscpp" "camera_info_manager" "image_transport" "nodelet" "sensor_msgs" "libv4l-dev" "gscam>")
set(i3dr_phobos_nuclear_BUILD_EXPORT_DEPENDS "roscpp" "camera_info_manager" "image_transport" "nodelet" "sensor_msgs" "libv4l-dev" "gscam>")
set(i3dr_phobos_nuclear_BUILDTOOL_DEPENDS "catkin")
set(i3dr_phobos_nuclear_BUILDTOOL_EXPORT_DEPENDS )
set(i3dr_phobos_nuclear_EXEC_DEPENDS "roscpp" "camera_info_manager" "image_transport" "nodelet" "sensor_msgs" "libv4l-dev" "gscam>")
set(i3dr_phobos_nuclear_RUN_DEPENDS "roscpp" "camera_info_manager" "image_transport" "nodelet" "sensor_msgs" "libv4l-dev" "gscam>")
set(i3dr_phobos_nuclear_TEST_DEPENDS )
set(i3dr_phobos_nuclear_DOC_DEPENDS )
set(i3dr_phobos_nuclear_URL_WEBSITE "http://i3drobotics.com/")
set(i3dr_phobos_nuclear_URL_BUGTRACKER "")
set(i3dr_phobos_nuclear_URL_REPOSITORY "")
set(i3dr_phobos_nuclear_DEPRECATED "")